name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [8.2] 

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

  
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, bcmath, pdo_sqlite, dom, curl, gd, xml
        coverage: none


    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

 
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use uma versão LTS do Node
        cache: 'npm'

    
    - name: Install NPM dependencies
      run: npm install

  
    - name: Build assets
      run: npm run build # 'npm run dev' não é ideal para CI, use 'build'


    - name: Copy .env file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

 
    - name: Create SQLite database
      run: touch database/database.sqlite

    - name: Run migrations
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan migrate --force

    # 9. Rodar os testes e o linter
    - name: Run PHPUnit tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: ./vendor/bin/phpunit

    - name: Run Laravel Pint (Code Style)
      run: ./vendor/bin/pint --test
